"""doctor notification_phone + whatsapp channel

Revision ID: 03f10a3c261f
Revises: 420a509fd880
Create Date: 2026-07-29 14:32:08.479569
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '03f10a3c261f'
down_revision: str | None = '420a509fd880'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('notification_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###
    # Novo valor do enum notification_channel (nome MAIÚSCULO, como o ORM grava).
    op.execute("ALTER TYPE notification_channel ADD VALUE IF NOT EXISTS 'WHATSAPP'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'notification_phone')
    # ### end Alembic commands ###
