"""appointment reminder_sent_at

Revision ID: 27d2543abe15
Revises: 64f7945387cb
Create Date: 2026-08-01 21:00:10.823302
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '27d2543abe15'
down_revision: str | None = '64f7945387cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminder_sent_at')
    # ### end Alembic commands ###
