"""doctor notification_email + onboarding audit action

Revision ID: 420a509fd880
Revises: 6618ac0da397
Create Date: 2026-07-29 13:10:24.806159
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '420a509fd880'
down_revision: str | None = '6618ac0da397'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('notification_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    # Novo valor do enum audit_action (nome MAIÚSCULO, como o ORM grava).
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'PATIENT_ONBOARDING_SENT'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'notification_email')
    # ### end Alembic commands ###
