"""medication intake reminded_at

Revision ID: 53df4f11af84
Revises: 6124225f1745
Create Date: 2026-08-01 20:05:08.325219
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '53df4f11af84'
down_revision: str | None = '6124225f1745'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_intakes', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_intakes', 'reminded_at')
    # ### end Alembic commands ###
