"""medication plans and intakes

Revision ID: 6124225f1745
Revises: 9909eb637324
Create Date: 2026-08-01 19:58:00.295572
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6124225f1745'
down_revision: str | None = '9909eb637324'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_plans',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.String(length=120), nullable=False),
    sa.Column('times', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_plans_patient_id'), 'medication_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_plans_tenant_id'), 'medication_plans', ['tenant_id'], unique=False)
    op.create_table('medication_intakes',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'TAKEN', 'LATER', 'MISSED', name='medication_intake_status'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['medication_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'scheduled_for', name='uq_intake_plan_schedule')
    )
    op.create_index(op.f('ix_medication_intakes_patient_id'), 'medication_intakes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_intakes_plan_id'), 'medication_intakes', ['plan_id'], unique=False)
    op.create_index(op.f('ix_medication_intakes_tenant_id'), 'medication_intakes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_intakes_tenant_id'), table_name='medication_intakes')
    op.drop_index(op.f('ix_medication_intakes_plan_id'), table_name='medication_intakes')
    op.drop_index(op.f('ix_medication_intakes_patient_id'), table_name='medication_intakes')
    op.drop_table('medication_intakes')
    op.drop_index(op.f('ix_medication_plans_tenant_id'), table_name='medication_plans')
    op.drop_index(op.f('ix_medication_plans_patient_id'), table_name='medication_plans')
    op.drop_table('medication_plans')
    # ### end Alembic commands ###
