"""multi-tenant foundation (tenants + tenant_id)

Revision ID: 9909eb637324
Revises: 3f57b72eb4f2
Create Date: 2026-07-30 19:29:56.820199
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9909eb637324'
down_revision: str | None = '3f57b72eb4f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('CLINIC', 'SOLO', name='tenant_kind'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_doctors_tenant_id'), 'doctors', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'doctors', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patients', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_column('patients', 'tenant_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_tenant_id'), table_name='doctors')
    op.drop_column('doctors', 'tenant_id')
    op.drop_table('tenants')
    # ### end Alembic commands ###
