"""add notifications table

Revision ID: 9d33ee353c6b
Revises: 02c848094e5d
Create Date: 2026-07-29 10:54:16.737347
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9d33ee353c6b'
down_revision: str | None = '02c848094e5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Novo valor do enum audit_action (autogenerate não detecta adições a enums).
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'alert_notification_sent'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('LOG', 'EMAIL', 'WEBHOOK', name='notification_channel'), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_alert_id'), 'notifications', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_alert_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS notification_status")
    op.execute("DROP TYPE IF EXISTS notification_channel")
    # Nota: o valor adicionado ao enum audit_action não é removido (PostgreSQL não
    # suporta remoção de valor de enum de forma trivial).
