"""exams

Revision ID: c64c326c258a
Revises: 27d2543abe15
Create Date: 2026-08-01 21:21:56.182426
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c64c326c258a'
down_revision: str | None = '27d2543abe15'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'AVAILABLE', name='exam_status'), nullable=False),
    sa.Column('result_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_doctor_id'), 'exams', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_exams_patient_id'), 'exams', ['patient_id'], unique=False)
    op.create_index(op.f('ix_exams_tenant_id'), 'exams', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_tenant_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_patient_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_doctor_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
