"""message thread (ai chat)

Revision ID: eb1c867da3db
Revises: 481310e70cf5
Create Date: 2026-08-03 23:52:26.274136
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eb1c867da3db'
down_revision: str | None = '481310e70cf5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Cria o tipo enum explicitamente (add_column não o cria sozinho no Postgres).
    message_thread = sa.Enum('CARE', 'AI', name='message_thread')
    message_thread.create(op.get_bind(), checkfirst=True)
    # server_default garante o preenchimento de linhas existentes (mensagens do chat
    # de cuidado já criadas). O valor é o NOME do enum, como o ORM grava.
    op.add_column(
        'messages',
        sa.Column(
            'thread',
            message_thread,
            nullable=False,
            server_default='CARE',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'thread')
    sa.Enum(name='message_thread').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
